Splitting box

diff --git a/box b/box
--- a/box
+++ b/box
@@ -2,38 +2,9 @@
 
 # Box: create namespaced script commands 
 
-set -e
-
-
 # Id: script.mpe
 
-box__load()
-{
-  test -d "$BOX_DIR" || mkdir -vp $BOX_DIR
-  test -n "$hostname" || hostname=$(hostname -s)
-  test "$(pwd)" = "$(pwd -P)" || warn "current dir seems to be aliased"
-  mkvid $(pwd)
-  nid_cwd=$vid
-  unset vid
-}
-
-box_commands()
-{
-  echo 'Commands:'
-  echo '    -r|run                      '
-  echo '    -h|help                     '
-  echo '    -e|edit                     Edit local script or abort. '
-  echo '    -E|edit-main                Edit main script. '
-  echo '    -i|init                     Init local script with name. '
-  echo '    -n|new                      '
-  echo '    -f|function                 '
-  echo ''
-}
-
-box_docs()
-{
-  echo 'Docs:'
-}
+set -e
 
 
 ### User commands
@@ -95,10 +66,10 @@ als__E=edit-main
 
 box_init_args()
 {
-  # cmd-name
+  # subcmd-name
   test -n "$1" && {
-    cmd_name="$1" ; c=$(( $c + 1 ))
-  } || cmd_name=run
+    subcmd_name="$1" ; c=$(( $c + 1 ))
+  } || subcmd_name=run
   # script-name
   test -n "$2" && {
     script_name="$2" ; c=$(( $c + 1 ))
@@ -112,7 +83,7 @@ main_1_init="Add script function, optionally providing command and script name"
 spc_init="-i|init [<cmd>=run [<name>=$hostname]]"
 c_init()
 {
-  local c=0 script_name= cmd_name= \
+  local c=0 script_name= subcmd_name= \
     global_func_name= local_func_name= \
     local_script= named_script= uconf_script=
 
@@ -127,7 +98,7 @@ c_init()
 EOF
 )"
 
-    where_grep='.*#.--.'${script_name}'.box.'${cmd_name}'.insert.*--'
+    where_grep='.*#.--.'${script_name}'.box.'${subcmd_name}'.insert.*--'
     #box_sentinel_indent $where_grep $named_script
     file_insert_where_before $where_grep $named_script "$(cat <<-EOF
   . $local_script
@@ -141,7 +112,7 @@ EOF
     box_add_function $global_func_name $named_script:$line_number "$(cat <<-EOF
   set -- # no-op
   # $local_func_name
-  # -- ${script_name} box ${cmd_name} insert sentinel --
+  # -- ${script_name} box ${subcmd_name} insert sentinel --
 EOF
 )
 "
@@ -170,8 +141,8 @@ EOF
 )"
 
   test -n "$script_name" \
-      && log "Extended $script_name with script $nid_cwd $cmd_name" \
-      || log "Created local script $nid_cwd $cmd_name"
+      && log "Extended $script_name with script $nid_cwd $subcmd_name" \
+      || log "Created local script $nid_cwd $subcmd_name"
 
   local files="$named_script $local_script $uconf_script"
   # XXX: vim only stuff
@@ -222,13 +193,15 @@ als__f=function
 man_1_="Default: require localscript. "
 c_()
 {
-  local c=0 script_name= cmd_name= \
+  local c=0 script_name= subcmd_name= \
     global_func_name= local_func_name= \
     local_script= named_script= uconf_script=
 
   box_init_args $@
   test $c -eq 0 || shift $c ; c=0
-  box_init_local || exit 1
+  box_init_local || { r=$?
+    test $r -eq 0 || error "$r error during box-init-local" $r
+  }
 
   # XXX list cmds? $UCONFDIR/box/${hostname}/index.sh list $(pwd)
   type run_box 1> /dev/null 2> /dev/null && {
@@ -259,7 +232,9 @@ c_run_global()
 
   box_init_args $@
   test $c -eq 0 || shift $c ; c=0
-  box_init_local || exit 1
+  box_init_local || { r=$?
+    test $r -eq 0 || error "$r error during box-init-local" $r
+  }
 
   type $global_func_name 2> /dev/null 1> /dev/null || {
     r=$?
@@ -287,7 +262,9 @@ c_run()
 
   box_init_args $@
   test $c -eq 0 || shift $c ; c=0
-  box_init_local 1 || exit 1
+  box_init_local || { r=$?
+    test $r -eq 0 || error "$r error during box-init-local" $r
+  }
 
   type $local_func_name 2> /dev/null 1> /dev/null || {
     r=$?
@@ -339,161 +316,6 @@ c_check_install()
 }
 
 
-### Util functions
-
-box_find_localscript()
-{
-  # XXX: or scan for function before determining script
-  test -e "$local_script" && return || {
-    warn "No local_script for $hostname:$(pwd)"
-    return 1
-  }
-}
-
-box_find_namedscript()
-{
-  named_script=$BOX_BIN_DIR/$script_name
-  test -e "$named_script" && return || {
-    warn "No named_script for $script_name"
-    return 1
-  }
-}
-
-box_req_files_localscript()
-{
-  local r=0
-
-  box_find_localscript && {
-    log "Including local-script $local_script"
-    . $local_script
-    script_files="$script_files $local_script"
-  } || r=1
-
-  box_find_namedscript && {
-    log "Including named-script $named_script"
-    . $named_script
-    script_files="$script_files $named_script"
-  } || r=$(( $r + 1 ))
-
-  test -e "$uconf_script" && {
-    log "Including uconf-script $uconf_script"
-    . $uconf_script
-    script_files="$script_files $uconf_script"
-  } || r=$(( $r + 1 ))
-
-  test $r -lt 3 || return $r
-}
-
-box_init_local()
-{
-  box_name="${script_name}:${script_subcmd_name}"
-  local_script=$BOX_DIR/${script_name}/${nid_cwd}.sh
-  uconf_script=$BOX_DIR/$script_name-localscripts.sh
-  #test -e $uconf_script && warn "TODO clean $uconf_script"
-  box_req_files_localscript
-  test -z "$1" -o $? -gt 0 || return 1
-  global_func_name=c_${script_name}__${script_subcmd_name}
-  local_func_name=c_${script_name}__local__${nid_cwd}__${script_subcmd_name}
-}
-
-box_init_script()
-{
-  touch $1
-  chmod +x $1
-  echo "#!/bin/sh" > $1
-  echo >> $1
-}
-
-# 1:func-name 2:file-name[:line-number] 3:script
-box_add_function()
-{
-  test -n "$1" || err "function name arg required" 1
-  test -n "$2" || err "file name arg required" 1
-  test -n "$3" || err "function body arg required" 1
-
-  fnmatch "*:[0-9]*" $2 && {
-
-    info "Inserting funtion $1"
-
-    file_insert_at $2 "$(cat <<-EOF
-$1()
-{
-$3
-}
-
-EOF
-)
-"
-
-  } || {
-
-    info "Appending funtion $1 for $2"
-
-    echo "$1()" >> $2
-    echo "{" >> $2
-    echo "$3" >> $2
-    echo "}" >> $2
-    echo >> $2
-  }
-}
-
-box_add_idx()
-{
-  echo "$1()" >> $2
-  echo "{" >> $2
-  echo "  $func" >> $2
-  echo "}" >> $2
-  echo >> $2
-}
-
-box_grep()
-{
-  file_where_before $1 $2
-  test -n "$where_line" || return 1
-}
-
-box_script_insert_point()
-{
-  local where_line= line_number=
-  local p='^'${script_name}'__main()$'
-  box_grep $p $1 || {
-    error "invalid ${script_name}__main ($1)" 1
-  }
-  echo $line_number
-}
-
-box_sentinel_indent()
-{
-  local where_line= line_number=
-  box_grep $1 $2 || {
-    error "invalid sentinel $1 ($2)" 1
-  }
-  echo "$where_line"
-}
-
-box_name_args()
-{
-  test -n "$1" && {
-    name="$1" ; shift 1 ; c=$(( $c + 1 ))
-  } || name="${hostname}"
-
-  test -n "$1" \
-    && { cmd="$1"; shift 1; c=$(( $c + 1 )); } \
-    || note "using default cmd='run'"
-}
-
-box_run_cwd()
-{
-  test -n "$1" || error "req name" 1
-  test -n "$2" || error "req cmd" 1
-  local func=$1__$2
-  local tcwd=$(echo $1 | tr '_' '/')
-  test -d $tcwd || error "no dir $tcwd" 1
-  shift 2
-  cd $tcwd
-  $func "$*"
-}
-
 
 ### Main
 
@@ -502,7 +324,7 @@ box__main()
   local scriptname=box base=$(basename $0 .sh) verbosity=5
 
   test -n "$PREFIX" || PREFIX=$HOME
-  . $PREFIX/bin/box-init.sh
+  . $PREFIX/bin/box.init.sh
 
   case "$base" in $scriptname )
 
@@ -523,8 +345,9 @@ box__main()
 
 box__init()
 {
-  . $PREFIX/bin/main.sh
   . $PREFIX/bin/util.sh
+  . $PREFIX/bin/main.sh
+  . $PREFIX/bin/box.lib.sh
 }
 
 # Use hyphen to ignore source exec in login shell
