Colors, dckr

diff --git a/dckr b/dckr
--- a/dckr
+++ b/dckr
@@ -89,7 +89,7 @@ dckr_name_argv()
   }
   test -z "$1" && name=$(basename $(pwd)) || name=$1
   dckr_name=${pref}${name}
-  test -n "$1" || log "Using dir for dckr-name: $dckr_name"
+_ test -n "$1" || info "Using dir for dckr-name: $dckr_name"
 }
 
 dckr_image_argv()
@@ -118,12 +118,7 @@ dckr_run()
   # pass hostname if set
   test -z "$dckr_hostname" || dckr_f="$dckr_f --hostname $dckr_hostname"
 
-  #echo dckr_name=$dckr_name
-  #echo dckr_f=$dckr_f
-  #echo dckr_argv=$dckr_argv
-  #echo dckr_cmd=$dckr_cmd
-
-  sudo docker run $@ $dckr_f \
+  sudo docker run $dckr_f $@ \
     --log-driver json-file \
     --name $dckr_name \
     --env DCKR_NAME=$dckr_name \
@@ -142,24 +137,29 @@ dckr_c()
   container=$(sudo docker ps $ps_f | grep '\<'$image_name'\>' | cut -f1 -d' ')
 }
 
+dckr_p()
+{
+  sudo docker ps | grep -q '\<'$dckr_name'\>' || return 1
+}
+
 dckr_stop()
 {
   test -n "$container" && {
-    echo "Stopping container $container:"
+    info "Stopping container $container:"
     sudo docker stop $container
     return
   }
   test -z "$dckr_name" && {
     test -z "$image_name" || {
-      log "Looking for running container by image-name $image_name:"
+      info "Looking for running container by image-name $image_name:"
       dckr_c
-      log "Stopping container by image-name $image_name:"
+      info "Stopping container by image-name $image_name:"
       sudo docker stop $container
     }
   } || {
     # check for container with name and remove
-    sudo docker ps | grep '\<'$dckr_name'\>' && {
-      log "Stopping container by container-name $dckr_name:"
+    sudo docker ps | grep -q '\<'$dckr_name'\>' && {
+      info "Stopping container by container-name $dckr_name:"
       sudo docker stop $dckr_name
     } || echo -n
   }
@@ -169,25 +169,26 @@ dckr_stop()
 dckr_rm()
 {
   test -n "$container" && {
-    echo "Removing container $container:"
+    note "Removing container $container:"
     sudo docker rm $container
     return
   }
   test -z "$dckr_name" && {
     test -z "$image_name" || {
-      log "Looking for container by image-name $image_name:"
+      debug "Looking for container by image-name $image_name:"
       dckr_c -a
-      log "Removing container $container"
+      info "Removing container $container"
       sudo docker rm $container
     }
   } || {
     # check for container with name and remove
-    sudo docker ps -a | grep '\<'$dckr_name'\>' && {
-      log "Removing container by container-name $dckr_name:"
+    sudo docker ps -a | grep -q '\<'$dckr_name'\>' && {
+      info "Removing container by container-name $dckr_name:"
       sudo docker rm $dckr_name
     } || echo -n
   }
 }
+
 
 dckr_start()
 {
@@ -206,7 +207,11 @@ dckr_names()
 
 dckr_ip()
 {
-  sudo docker inspect --format '{{ .NetworkSettings.IPAddress }}' $1
+  test -n "$1" || set -- $container
+  test -n "$1" || set -- $dckr_name
+  test -n "$1" || error "dckr-ip: container required" 1
+  sudo docker inspect --format '{{ .NetworkSettings.IPAddress }}' $1 \
+    || error "docker IP inspect on $1 failed" 1
 }
 
 dckr__man_1_ps="Docker ps"
@@ -234,7 +239,6 @@ dckr__man_1_rm="Remove image. "
 dckr__rm()
 {
   note "Removing and stopping container.."
-  dckr__stop
   dckr_rm
 }
 
@@ -272,6 +276,15 @@ dckr__ip()
       test -z "$ip" || echo "$ip  $dckr_name "
     done
   }
+}
+
+dckr__man_1_destroy="Clean given container names. "
+dckr__spc_destroy='[-f] destroy'
+dckr__destroy()
+{
+  local f= ; test -n "$choice_force" || f="-f"
+  while [ $# -gt 0 ]
+  do sudo docker rm $f $1 ; shift ; done
 }
 
 dckr__man_1_dnsmasq_conf="dnsmasq static address config using image-name as hostname"
@@ -390,26 +403,66 @@ dckr__script()
   echo sudo docker exec -ti $dckr_name /tmp/$dckr_script
 }
 
+dckr__exec()
+{
+  test -z "$1" || image_name="$1"
+  test -z "$2" || dckr_cmd="$@"
+  sudo docker exec -ti "$image_name" "$dckr_cmd"
+}
 
-# FIXME: abstract below cmds so things can move to config files
 
-# FIXME: something to persist here?
-dckr__init_shipyard()
+dckr__man_1_shipyard_options="Show currently available deploy help. "\
+'
+  ACTION: this is the action to use (deploy, upgrade, remove)
+  IMAGE: this overrides the default Shipyard image
+  PREFIX: prefix for container names
+  SHIPYARD_ARGS: these are passed to the Shipyard controller container as controller args
+  TLS_CERT_PATH: path to certs to enable TLS for Shipyard
+'
+dckr__shipyard_options()
+{
+  curl -s https://shipyard-project.com/deploy | bash -s -- -h
+}
+
+dckr__man_1_shipyard_init="Deploy Shipyard at 8080"
+dckr__shipyard_init()
+{
+  note "Initializing VS1 Shipyard"
+  local dckr_name=shipyard-rethinkdb
+  dckr_p && {
+    echo -n "Shipyard at vs1:8080 running from IP "
+    dckr_ip
+  } || {
+    sudo bash -c ' curl -s https://shipyard-project.com/deploy | bash -s '
+  }
+}
+
+dckr__man_1_shipyard_init_old="Shutdown and boot shipard at 8001"
+dckr__shipyard_init_old()
 {
   for dckr_name in shipyard shipyard-rethinkdb-data shipyard-rethinkdb
   do
     dckr_stop && dckr_rm || error "Error destroying $dckr_name" 1
   done
 
-  sudo docker run -it -d --name shipyard-rethinkdb-data --entrypoint /bin/bash shipyard/rethinkdb -l
+  sudo docker run -it -d -l \
+    --name shipyard-rethinkdb-data \
+    --entrypoint /bin/bash shipyard/rethinkdb
   sleep 2
 
-  sudo docker run -it -d --name shipyard-rethinkdb --volumes-from shipyard-rethinkdb-data shipyard/rethinkdb
+  sudo docker run -it -d \
+    --name shipyard-rethinkdb \
+    --volumes-from shipyard-rethinkdb-data shipyard/rethinkdb
   sleep 4
 
-  sudo docker run -it -p 8001:8080 -d --name shipyard --link shipyard-rethinkdb:rethinkdb shipyard/shipyard
+  sudo docker run -it -d \
+    -p 8001:8080 \
+    --name shipyard \
+    --link shipyard-rethinkdb:rethinkdb shipyard/shipyard
 }
 
+
+dckr__man_1_init_cadvisor="Run cAdvisor at 8002"
 dckr__init_cadvisor()
 {
   sudo docker run \
@@ -422,8 +475,26 @@ dckr__init_cadvisor()
     --name=cadvisor \
     google/cadvisor:latest
 
-#-storage_driver=influxdb
+# XXX -storage_driver=influxdb
 }
+
+
+dckr__man_init_sickbeard="Rebuild sickbeard at 8008"
+dckr__init_sickbeard()
+{
+  dckr_f_argv $@
+  image_name=sickbeard
+  dckr_name=${pref}sickbeard
+  cd ~/project/docker-sickbeard
+  dckr_build && \
+  dckr_rm && \
+  dckr_run \
+    -p 8008:8081 \
+    -v $DCKR_VOL/sickbeard/data:/data:rw \
+    -v $DCKR_VOL/sickbeard/config:/config:rw \
+    -v /etc/localtime:/etc/localtime:ro
+}
+
 
 dckr__reset_munin()
 {
@@ -456,12 +527,14 @@ dckr__run_munin()
   dckr_name=scalingo_munin
   dckr_run \
     -p 8003:8080 \
-    -v $DCKR_VOL/munin/logs:/var/log/munin:rw \
+    -v $DCKR_VOL/munin/logs:/var/info/munin:rw \
     -v $DCKR_VOL/munin/db:/var/lib/munin:rw \
     -v $DCKR_VOL/munin/run:/var/run/munin:rw \
     -v $DCKR_VOL/munin/munin:/var/cache/munin:rw \
     -v /etc/localtime:/etc/localtime:ro
 }
+
+
 
 dckr__reset_sandbox()
 {
@@ -499,21 +572,6 @@ dckr__init_weather()
     -p 8004:8080 \
     --link ${pref}weather:${pref}weather \
     -v $DCKR_VOL/ssh:/docker-ssh:ro \
-    -v /etc/localtime:/etc/localtime:ro
-}
-
-dckr__init_sickbeard()
-{
-  dckr_f_argv $@
-  image_name=sickbeard
-  dckr_name=${pref}sickbeard
-  cd ~/project/docker-sickbeard
-  dckr_build && \
-  dckr_rm && \
-  dckr_run \
-    -p 8008:8081 \
-    -v $DCKR_VOL/sickbeard/data:/data:rw \
-    -v $DCKR_VOL/sickbeard/config:/config:rw \
     -v /etc/localtime:/etc/localtime:ro
 }
 
@@ -595,29 +653,6 @@ dckr__init_dev()
   dckr_run
 }
 
-# Jenkins
-
-dckr__reset_jenkins()
-{
-  cd ~/project/docker-jenkins-mpe
-  ./build.sh
-}
-
-# Start fresh jenkins-mpe with name ${pref}jenkins. Stops/removes running container.
-# $ 1:tag 2:port 3:flags
-dckr__init_jenkins()
-{
-  cd ~/project/docker-jenkins-mpe
-}
-
-# Initialize running jenkins-mpe, using JJB to setup jobs
-dckr__update_jenkins()
-{
-  cd ~/project/docker-jenkins-mpe
-  ./config.sh
-}
-
-
 # OpenWRT
 
 # could import from tar
@@ -646,6 +681,86 @@ dckr__build_openwrt()
   dckr_run \
     -v /src/openwrt:/src/openwrt \
     -u builder
+}
+
+
+
+# Lib
+
+dckr_man_1_redock=\
+'
+  If container is running, leave image unless forced. Otherwise delete
+  for rebuild. Then build and run image. Finish with ps line and IP address.
+'
+dckr_spc_redock='redock <image-name> <dckr-name> [<tag>=latest]'
+dckr_redock()
+{
+  local reset= image_name= dckr_name= tag=
+
+  dckr_rebuild "$@"
+
+  # Run if needed and stat
+  sudo docker ps -a | grep -q '\<'$dckr_name'\>' && {
+    test -z "$reset" || error "still running? $dckr_name" 3
+  } || {
+    sudo docker run -dt --name $dckr_name \
+      $image_name:${tag}
+  }
+
+  echo "$dckr_name proc: "
+  sudo docker ps -a | grep '\<'$dckr_name'\>'
+  dckr ip $dckr_name
+}
+
+dckr_rebuild()
+{
+  test -z "$choice_force" || reset=1
+
+  test -z "$1" || image_name=$1
+  test -n "$image_name" || error "image-name required" 1
+
+  test -z "$2" || dckr_name=$2
+  test -n "$dckr_name" || error "dckr-name required" 1
+
+  test -z "$3" || tag=$3
+  test -n "$tag" || tag=latest
+
+  test -n "$choice_force" \
+    && info "Rebuilding container $dckr_name" \
+    || info "Rebuilding offline $dckr_name"
+
+  # Remove if needed/wanted
+  sudo docker ps -a | grep -q '\<'$dckr_name'\>' && {
+
+    sudo docker ps | grep -q '\<'$dckr_name'\>' && {
+
+      test -z "$reset" || {
+        note "Forcing remove of existing image"
+        sudo docker rm -f $dckr_name
+      }
+
+    } || {
+      debug "Container $dckr_name exists but does not seem to be running, rebuilding"
+      sudo docker rm $dckr_name
+    }
+  }
+
+  sudo docker ps -a | grep -q '\ \<'$dckr_name'\>\ ' || {
+
+    #sudo docker rmi -f $image_name:$tag
+
+    # Build
+    match_grep_pattern_test "$image_name:$tag"
+    sudo docker images | grep -q $p_ && {
+
+      info "Reusing existing ${image_name}:${tag} image"
+    } || {
+
+      debug "Building new ${image_name}:${tag} image"
+      sudo docker build -t ${image_name}:${tag} .
+      info "Done building ${image_name}:${tag} image"
+    }
+  }
 }
 
 
