Htd, dckr script upd

diff --git a/dckr b/dckr
--- a/dckr
+++ b/dckr
@@ -786,6 +786,87 @@ dckr_rebuild()
 }
 
 
+# Setup correct IP's in host
+# exit 1 on error, 2 on updated, 0 on no-op
+dckr__machine_ip_update()
+{
+  test -n "$1" || set -- "dev"
+  test "$(docker-machine status $1)" = "Running" \
+    || note "Not running: docker machine $1" 1
+  docker_machine_ip=$(docker-machine ip $1)
+  case "$1" in
+    prod )
+      docker_domain=docker.simza.lan
+      ;;
+    * )
+      docker_domain=docker-$1.simza.lan
+      ;;
+  esac
+  grep -q '^'$docker_machine_ip'\ *'$docker_domain'$' /etc/hosts && {
+    note "IP for '$1' ($docker_domain) still '$docker_machine_ip'"  
+  } || {
+    sudo sed -i.bak 's/^[0-9\.]*\ \ *'$docker_domain'$/'$docker_machine_ip'   '$docker_domain'/' /etc/hosts \
+      && warn "Updated IP ($docker_machine_ip) for '$1' ($docker_domain)" 2 \
+      || error "Unable to upate IP ($docker_machine_ip) for '$1' ($docker_domain)" 1
+  }
+}
+
+# Add NFS export entry for docker share
+dckr__machines_nfs()
+{
+  test -n "$1" || set -- $(docker-machine ls -q)
+  local updated=/tmp/dckr-machines-nfs-$(uuidgen)
+  while test -n "$1"
+  do
+    #test "$(docker-machine status $1)" = "Running" || { shift; continue; }
+    note "Updating NFS for '$1' ..."
+    #docker-machine-nfs "$1" --shared-folder=/Volumes/Simza/docker --nfs-config="-alldirs -mapall=501:1000"
+    #docker-machine-nfs "$1" --shared-folder=/Volumes/Simza/docker --nfs-config="-alldirs -maproot=0"
+    docker-machine-nfs "$1" --shared-folder=/Volumes/Simza/docker --force \
+      && note "Reinitialized NFS for '$1'" \
+      || { note "Error in NFS init for '$1'"; echo $1>$updated; } \
+
+    shift
+  done
+  test ! -e "$updated" || {
+    machines="$(echo "$(cat $updated)")"
+    rm $updated
+    error "Failures on (some) machines: $machines" 1
+  }
+}
+
+# return 1 on error, 2 on updated, 0 on no-op
+dckr__machines()
+{
+  test -n "$1" || set -- $(docker-machine ls -q)
+  local updated=/tmp/dckr-machines-ip-updated-$(uuidgen)
+  test ! -e "$updated" || rm $updated
+  test -e /etc/exports || sudo touch /etc/exports
+  while test -n "$1"
+  do
+    test "$(docker-machine status $1)" = "Running" || { shift; continue; }
+    note "Updating '$1' ..."
+    dckr machine-ip-update $1 || {
+      case "$?" in 1 ) return 1;; 2 ) echo $1>$updated ;; esac
+    }
+    grep -qF $(docker-machine ip $1) /etc/exports || {
+      echo "$1">$updated
+    }
+    shift
+  done
+  test ! -e "$updated" || {
+    machines="$(echo "$(cat $updated)")"
+    rm $updated
+    warn "Updates found"
+    # XXX: maybe better check with u-c before removing, not needed for now
+    test ! -e /etc/exports || sudo rm /etc/exports
+    test -e /etc/exports || sudo touch /etc/exports
+    note "Updating NFS for all running machines" #'$machines'"
+    dckr machines-nfs || return 1
+    return 2
+  }
+}
+
 # include private projects
 test ! -e $DCKR_CONF/local.sh || {
   . $DCKR_CONF/local.sh
