New git-contains and git-annex-contains commands

diff --git a/htd b/htd
--- a/htd
+++ b/htd
@@ -1111,6 +1111,38 @@ c_git_annex_clear_unused()
   }
 }
 
+c_git_contains()
+{
+  test -n "$1" || error "expected file path argument" 1
+  test -f "$1" || error "not a file path argument '$1'" 1
+  test -n "$2" || set -- "$1" "."
+  test -z "$3" || error ""
+
+  sha1="$(git hash-object "$1")"
+  echo "SHA1: $sha1"
+
+  { ( cd "$2" ; git rev-list --objects --all | grep "$sha1" ); } && {
+    echo "Found regular GIT object"
+  } || c_git_annex_contains "$1" "$2" || {
+    echo "Unable to find path in GIT at @$2: '$1'"
+  }
+}
+
+c_git_annex_contains()
+{
+  test -n "$1" || error "expected file path argument" 1
+  test -f "$1" || error "not a file path argument '$1'" 1
+  test -n "$2" || set -- "$1" "."
+  test -z "$3" || error ""
+
+  size="$(stat -Lf '%z' "$1")"
+  sha256="$(shasum -a 256 "$1" | cut -f 1 -d ' ')"
+  keyglob='*s'$size'--'$sha256'.*'
+  echo "SHA256E key glob: $keyglob"
+  { find $2 -ilname $keyglob | while read path; do echo $path;ls -la $path; done } || info "Found nothing for '$keyglob'"
+}
+
+
 # indexing, cleaning
 
 htd_name_precaution() {
