Accum

diff --git a/htd b/htd
--- a/htd
+++ b/htd
@@ -1667,6 +1667,35 @@ c_tmux_tw()
 }
 
 
+c_reader_update()
+{
+  {
+    cd /Volumes/READER
+
+    for remote in .git/refs/remotes/*
+    do
+      name="$(basename "$remote")"
+      younger_than "$remote" _1HOUR && {
+        info "Remote $name is up-to-date"
+      } || {
+        note "Remote $name is too old, syncing"
+        git annex sync $name
+      }
+    done
+
+    info "Removing dead symlinks (annex content elsewhere), for PRS software"
+    find ./ -type l | while read l
+    do
+        test -e "$l" || rm "$l"
+    done
+
+  } && {
+    note "Reader is up to date"
+  } || {
+    warn "Error(s) updating reader"
+  }
+}
+
 c_man_1_test="no test, just checking it goes"
 c_test()
 {
@@ -1720,6 +1749,7 @@ htd_init()
   . $PREFIX/bin/main.sh
   . $PREFIX/bin/main.init.sh
   . $PREFIX/bin/box.lib.sh
+  . $PREFIX/bin/date.lib.sh
   # -- htd box init sentinel --
 }
 
