-

diff --git a/htd b/htd
--- a/htd
+++ b/htd
@@ -1766,6 +1766,15 @@ c_mp3_validate()
   done
 }
 
+c_mux()
+{
+  test -n "$1" || set -- "docker-"
+  test -n "$2" || set -- "$1" "dev"
+  test -n "$3" || set -- "$1" "$2" "$(hostname -s)"
+
+  note "tmuxinator start $1 $2 $3"
+  tmuxinator start $1 $2 $3
+}
 
 c_tmux_prive()
 {
@@ -1774,22 +1783,22 @@ c_tmux_prive()
   case "$1" in init|"*" )
   tmux has-session -t Prive >/dev/null || {
     c_tmux_init Prive
-    tmux send-keys -t Prive:1 "reset;cd;git st" enter
+    tmux send-keys -t Prive:1 "cd;simza test" enter
   }
   tmux list-windows -t Prive | grep -q HtD || {
     tmux new-window -t Prive -n HtD
-    tmux send-keys -t Prive:HtD "reset;cd ~/htdocs/; htd today personal/journal;git st" enter
+    tmux send-keys -t Prive:HtD "cd ~/htdocs/; htd today personal/journal;git st" enter
     tmux send-keys -t Prive:HtD "git add -u;git add dev/ personal/*.rst personal/journal/2*.rst sysadmin/*.rst *.rst;git st" enter
     note "Initialized 'HtD' window"
   }
   tmux list-windows -t Prive | grep -q '\ conf' || {
     tmux new-window -t Prive -n conf
-    tmux send-keys -t Prive:conf "reset;cd ~/.conf;git st" enter
+    tmux send-keys -t Prive:conf "cd ~/.conf;git st" enter
     note "Initialized 'conf' window"
   }
   tmux list-windows -t Prive | grep -q Bin || {
     tmux new-window -t Prive -n Bin
-    tmux send-keys -t Prive:Bin "reset;cd ~/bin;git st" enter
+    tmux send-keys -t Prive:Bin "cd ~/bin;git st" enter
     note "Initialized 'Bin' window"
   }
   ;; esac
@@ -1797,32 +1806,32 @@ c_tmux_prive()
   case "$1" in ino|"*" )
   tmux list-windows -t Prive | grep -q Ino || {
     tmux new-window -t Prive -n Ino
-    tmux send-keys -t Prive:Ino "reset;cd ~/project/arduino-docs;git st" enter
+    tmux send-keys -t Prive:Ino "cd ~/project/arduino-docs;git st" enter
     note "Initialized 'Ino' window"
   }
   ;; esac
   case "$1" in eagle|"*" )
   tmux list-windows -t Prive | grep -q EAGLE || {
     tmux new-window -t Prive -n EAGLE
-    tmux send-keys -t Prive:EAGLE "reset;cd ~/project/Eagle-mpe;git st" enter
+    tmux send-keys -t Prive:EAGLE "cd ~/project/Eagle-mpe;git st" enter
     note "Initialized 'EAGLE' window"
   }
   ;; esac
   #tmux list-windows -t Prive | grep -q Loci || {
   #  tmux new-window -t Prive -n Loci
-  #  tmux send-keys -t Prive:Loci "reset;cd ~/project/node-loci;git st" enter
+  #  tmux send-keys -t Prive:Loci "cd ~/project/node-loci;git st" enter
   #}
   case "$1" in sf|"*" )
   tmux list-windows -t Prive | grep -q Sf || {
     tmux new-window -t Prive -n Sf
-    tmux send-keys -t Prive:Sf "reset;cd ~/project/node-sitefile;git st" enter
+    tmux send-keys -t Prive:Sf "cd ~/project/node-sitefile;git st" enter
     note "Initialized SiteFile [Sf] window"
   }
   ;; esac
   case "$1" in docs|"*" )
   tmux list-windows -t Prive | grep -q Docs || {
     tmux new-window -t Prive -n Docs
-    tmux send-keys -t Prive:Docs "reset;cd ~/Documents/;git st" enter
+    tmux send-keys -t Prive:Docs "cd ~/Documents/;git st" enter
     note "Initialized Documents window"
   }
   ;; esac
@@ -1833,7 +1842,7 @@ c_tmux_work()
   test -n "$1" || set -- "*"
   cd ~/work/brix
 
-  # Make sure Work session is registered with tmux server
+  ### Make sure Work session is registered with tmux server
 
   case "$1" in init|"*" )
 
@@ -1852,7 +1861,7 @@ c_tmux_work()
 
   tmux list-windows -t Work | grep -q '1:\ Log' || {
     tmux new-window -t Work -n Log
-    tmux send-keys -t Work:Log "reset;cd ~/work/brix/;htd today log" enter
+    tmux send-keys -t Work:Log "cd ~/work/brix/;htd today log" enter
     tmux send-keys -t Work:Log "(cd log;git add -u;git add 20*.rst; git st)" enter
   }
   sleep 1
@@ -1863,62 +1872,64 @@ c_tmux_work()
 
   ;; esac
 
-  # Add other windows
+
+  ### Add other windows
 
   case "$1" in tree|"*" )
   tmux list-windows -t Work | grep -q Tree || {
     tmux new-window -t Work -n Tree
-    tmux send-keys -t Work:Tree "reset;cd ~/work/brix/" enter "make status" enter
+    tmux send-keys -t Work:Tree "cd ~/work/brix/" enter "make status" enter
     note "Initialized Tree window"
   }
   ;; esac
   case "$1" in cln|"*" )
   tmux list-windows -t Work | grep -q Cleaning || {
     tmux new-window -t Work -n TreeCln
-    tmux send-keys -t Work:TreeCln "reset;cd /Volumes/Simza/WorkCleaning/brix" enter "make status" enter
+    tmux send-keys -t Work:TreeCln "cd /Volumes/Simza/WorkCleaning/brix" enter "make status" enter
     note "Initialized TreeCln window"
   }
   ;; esac
-
-  case "$1" in jenkins|"*" )
-  tmux list-windows -t Work | grep -q Jnk || {
-    tmux new-window -t Work -n Jnk
-    tmux send-keys -t Work:Jnk "reset;cd ~/work/brix/Jenkins;ls -la" enter
-    note "Initialized Jnk window"
-  }
-  #tmux list-windows -t Work | grep -q DvD || {
-  #  tmux new-window -t Work -n DvD
-  #  tmux send-keys -t Work:DvD "reset;cd ~/work/brix/tree/dev-doc;git fetch --all;git st" enter
-  #}
-  #tmux list-windows -t Work | grep -q Skl || {
-  #  tmux new-window -t Work -n Skl
-  #  tmux send-keys -t Work:Skl "reset;cd ~/work/brix/tree/project-skeleton-ng" enter "git st" enter
-  #}
+  case "$1" in jenkins )
+      htd tmux-winit Work Jnk ~/work/brix/tree/Jenkins \
+        "(cd jenkins-ci-config && git fetch --all && git status); (cd userContent && git fetch --all && git status)"
   ;; esac
-
+  case "$1" in dev-doc )
+      htd tmux-winit Work DvD ~/work/brix/tree/dev-doc
+  ;; esac
+  case "$1" in skel* )
+      htd tmux-winit Work Skl ~/work/brix/tree/project-skeleton-ng
+  ;; esac
   case "$1" in mango|"*" )
-  tmux list-windows -t Work | grep -q MngB || {
-    tmux new-window -t Work -n MngB
-    tmux send-keys -t Work:MngB "reset;cd /Volumes/Simza/WorkCleaning/brix/tree/mango-builds" enter "git st" enter
-    note "Initialized MngB window"
-  }
+      htd tmux-winit Work MngB /Volumes/Simza/WorkCleaning/brix/tree/mango-builds
   ;; esac
 
   case "$1" in studio|"*" )
   tmux list-windows -t Work | grep -q BrxStd || {
     tmux new-window -t Work -n BrxStd
-    tmux send-keys -t Work:BrxStd "reset;cd /Volumes/Simza/WorkCleaning/brix/tree/brixcloud-studio-testing" enter "git st" enter
+    tmux send-keys -t Work:BrxStd "cd /Volumes/Simza/WorkCleaning/brix/tree/brixcloud-studio-testing" enter "git st" enter
     note "Initialized BrxStd window"
   }
   tmux list-windows -t Work | grep -q BrxStdT || {
     tmux new-window -t Work -n BrxStdT
-    tmux send-keys -t Work:BrxStdT "reset;cd /Volumes/Simza/WorkCleaning/brix/tree/brixcloud-studio-testing2;ls -la" enter
+    tmux send-keys -t Work:BrxStdT "cd /Volumes/Simza/WorkCleaning/brix/tree/brixcloud-studio-testing2;ls -la" enter
     note "Initialized BrxStdT window"
   }
   tmux list-windows -t Work | grep -q BrxStdSkl || {
     tmux new-window -t Work -n BrxStdSkl
-    tmux send-keys -t Work:BrxStdSkl "reset;cd ~/work/brix/tree/brixcloud-studio-skeleton" enter "git st" enter
+    tmux send-keys -t Work:BrxStdSkl "cd ~/work/brix/tree/brixcloud-studio-skeleton" enter "git st" enter
     note "Initialized BrxStdSkl window"
+  }
+  ;; esac
+
+
+  ### Clients
+
+  case "$1" in sw|stein*|steinweg )
+  tmux list-windows -t Work | grep -q Sw || {
+    tmux new-window -t Work -n Sw
+    # TODO
+    tmux send-keys -t Work:Sw "cd /Volumes/Simza/work/brix/tree/steinweg" enter "git st" enter
+    note "Initialized Sw window"
   }
   ;; esac
 }
@@ -1928,26 +1939,57 @@ c_tmux_srv()
   cd /srv
   tmux has-session -t Srv >/dev/null || {
     c_tmux_init Srv
-    tmux send-keys -t Srv:bash "reset; cd ~/.conf; ./script/update.sh" enter
+    tmux send-keys -t Srv:bash "cd ~/.conf; ./script/update.sh" enter
   }
   tmux list-windows -t Srv | grep -q HtD-Sf || {
     tmux new-window -t Srv -n HtD-Sf
-    tmux send-keys -t Srv:HtD-Sf "reset; cd ~/htdocs/; sitefile" enter
+    tmux send-keys -t Srv:HtD-Sf "cd ~/htdocs/; sitefile" enter
   }
   tmux list-windows -t Srv | grep -q BrX-Sf || {
     tmux new-window -t Srv -n BrX-Sf
-    tmux send-keys -t Srv:BrX-Sf "reset; cd ~/work/brix/; sitefile" enter
+    tmux send-keys -t Srv:BrX-Sf "cd ~/work/brix/; sitefile" enter
   }
   tmux list-windows -t Srv | grep -q X-Tw || {
     tmux new-window -t Srv -n X-Tw
-    tmux send-keys -t Srv:X-Tw "reset; cd ~/project/x-tiddlywiki; tiddlywiki x-tiddlywiki --server" enter
+    tmux send-keys -t Srv:X-Tw "cd ~/project/x-tiddlywiki; tiddlywiki x-tiddlywiki --server" enter
   }
   tmux list-windows -t Srv | grep -q Loci || {
     tmux new-window -t Srv -n Loci
-    tmux send-keys -t Srv:Loci "reset; cd ~/project/node-loci; npm start" enter
+    tmux send-keys -t Srv:Loci "cd ~/project/node-loci; npm start" enter
   }
 }
 
+
+# htd tmux-winit SESSION WINDOW DIR CMD
+c_tmux_winit()
+{
+  ## Parse args
+  test -n "$1" || error "Session <arg1> required" 1
+  test -n "$2" || error "Window <arg2> required" 1
+  test -n "$3" || {
+    # set working dir
+    case "$1" in
+      Work )
+        set -- "$1" "$2" "~/work/brix/tree/$2" ;;
+      Prive )
+        set -- "$1" "$2" "~/project/$2" ;;
+      * ) 
+        error "Cannot setup working-dir for window '$1:$2'" 1 ;;
+    esac
+  }
+  test -d "$3" || error "Expected <arg3> to be directory '$3'" 1
+  test -n "$4" || {
+    set -- "$1" "$2" "$3" "git fetch --all && status" 
+  }
+
+  tmux list-windows -t $1 | grep -q $2 && {
+    note "Window '$1:$2' already initialized"
+  } || {
+    tmux new-window -t $1 -n $2
+    tmux send-keys -t $1:$2 "cd $3" enter "$4" enter
+    note "Initialized '$1:$2' window"
+  }
+}
 
 c_tmux_init()
 {
