Testing

diff --git a/sh-sync b/sh-sync
--- a/sh-sync
+++ b/sh-sync
@@ -1,5 +1,47 @@
 #!/bin/sh
 
+# Keep build tooling copies in sync
+
+remove_dupes() # ~
+{
+  awk '!a[$0]++'
+}
+
+unique_files() # PATHNAME...
+{
+  for path in "$@"
+  do
+    test -e "$path" && realpath "$path" || echo "$path"
+  done | remove_dupes
+}
+
+diff_files() # FILEPATH PATHNAME...
+{
+  local from="$1"
+  shift
+  for path in "$@"
+  do
+    test -f "$path" || path="$path/$1"
+    diff -bqr "$1" "$path" && continue
+  done
+}
+
+set -e
+
+set -- $(unique_files "$PWD/.git/hooks/pre-commit" $HOME/.git-pre-commit* | \
+    tr '\n' ' ')
+diff_files "$@" || vimdiff "$@" || true
+
+set -- $(unique_files \
+    ~/bin/.travis.y*ml \
+    ~/project/*script*/.travis.y*ml \
+    ~/project/x-ci*/.travis.y*ml \
+  | \
+    tr '\n' ' ')
+diff_files "$@" || vimdiff "$@" || true
+
+
+# TODO: cleanup, diff these too, later.
 #tools/sh/init.sh
 #tools/sh/init-here.sh
 #tools/sh/log.sh
@@ -8,33 +50,42 @@
 
 #$(echo tools/ci/parts/*.sh)
 
-for x in `cat <<EOM
-tools/sh/boot/null.sh
-tools/sh/boot/script.sh
-tools/sh/boot/std.sh
-tools/sh/boot/stderr-console-logger.sh
-tools/sh/boot/test.sh
+#tools/sh/boot/null.sh
+#tools/sh/boot/script.sh
+#tools/sh/boot/std.sh
+#tools/sh/boot/stderr-console-logger.sh
+#tools/sh/boot/test.sh
+
+# For each given path (remove glob duplicates but don't re-sort)
+for x in ` remove_dupes <<EOM
+
+sh-main
+sh-baseline.tab
 tools/sh/build/dev.sh
 tools/sh/build/test.sh
 tools/sh/parts/env-0.sh
-$(echo tools/sh/parts/env-*.sh)
+$(echo tools/sh/parts/env-*.sh | tr ' ' '\n')
 tools/sh/parts/init.sh
 tools/sh/parts/print-color.sh
 tools/sh/bats-colorize.sh
 tools/sh/run.sh
 tools/sh/util.sh
-$(echo tools/ci/*.sh)
+$(echo tools/ci/*.sh | tr ' ' '\n')
 tools/sh/user-env.sh
 tools/sh/env.sh
 tools/ci/env.sh
+
 EOM
 `; do
   test -n "$x" || continue
+  # TODO: limit diff dirs
 
-  test -e ~/bin/$x -o -e ~/htdocs/$x \
-      -o -e ~/project/user-scripts/$x \
-      -o -e ~/project/user-scripts-incubator/$x || {
+  test -e ~/bin/"$x" -o -e ~/htdocs/"$x" \
+      -o -e ~/.conf/"$x" \
+      -o -e ~/project/user-scripts/"$x" \
+      -o -e ~/project/user-scripts-incubator/"$x" || {
 
+    case "$x" in *"*"* ) continue ;; esac
     echo "# No such file '$x'" >&2
     exit 100
   }
@@ -43,7 +94,11 @@ EOM
   #test -e ~/bin/$x -o -e ~/htdocs/$x  \
   #    -o -e ~/user-scripts/$x || touch ~/bin/$x
 
-  diff -bqr ~/bin/$x ~/project/user-scripts/$x && continue
+  test -h "$PWD/$x" && continue
 
-  vimdiff ~/"bin/$x" ~/"project/user-scripts/$x" ~/"htdocs/$x"
+  diff -bqr $PWD/"$x" ~/project/user-scripts/"$x" && continue
+
+  vimdiff $( unique_files \
+      ~/"bin/$x" ~/"project/user-scripts/$x" ~/"htdocs/$x" ~/.conf/"$x" || \
+      return )
 done
